name = "WeakKeyIdDicts"
uuid = "ecbed89c-9d59-4137-ae1f-d1084086d01c"
authors = ["Beacon Biosignals, Inc"]
version = "0.1.0"

[compat]
Aqua = "0.8"
julia = "1.6"
Test = "1.0"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
